### ISSUE TITLE
UWP not loading SVG (net standard 2.0)

### ISSUE THREAD

**Issue by patsadow2** [luberda-molinet/FFImageLoading#1048]
Could not load SVG in UWP version 2.4. 

Image loading failed: https://upload.wikimedia.org/wikipedia/commons/c/c9/Svg_example4.svg;(size=0x0,dip=True,type=SvgDataResolver)
System.NullReferenceException: Object reference not set to an instance of an object.
   at FFImageLoading.Work.PlatformImageLoaderTask`1.

It's working on version 2.3.5

**Comment by daniel-luberda** [comment]
Could you provide a full stack trace?

**Comment by JTOne123** [comment]
the same https://github.com/luberda-molinet/FFImageLoading/issues/779

`[PERFORMANCE] Scheduler - Max: 4, Pending: 0, Running: 3, TotalPending: 3, TotalRunning: 3, TotalMemoryCacheHit: 0, TotalWaiting: 0Generating/retrieving image: resource://SharedSvgSample.Resources.bug.svg?assembly=SharedSvgSample,%20Version=1.0.0.0,%20Culture=neutral,%20PublicKeyToken=null;(size=0x100,dip=True,type=SvgDataResolver)[PERFORMANCE] Memory - not implemented[PERFORMANCE] Scheduler - Max: 4, Pending: 0, Running: 3, TotalPending: 3, TotalRunning: 3, TotalMemoryCacheHit: 0, TotalWaiting: 0[PERFORMANCE] Memory - not implementedGenerating/retrieving image: resource://SharedSvgSample.Resources.fingerprint.svg?assembly=SharedSvgSample,%20Version=1.0.0.0,%20Culture=neutral,%20PublicKeyToken=null;(size=0x100,dip=True,type=SvgDataResolver)Generating/retrieving image: resource://SharedSvgSample.Resources.camera.svg?assembly=SharedSvgSample,%20Version=1.0.0.0,%20Culture=neutral,%20PublicKeyToken=null;(size=0x100,dip=True,type=SvgDataResolver)Exception thrown: 'System.NullReferenceException' in FFImageLoading.Platform.dll
Exception thrown: 'System.NullReferenceException' in FFImageLoading.Platform.dll
Exception thrown: 'System.NullReferenceException' in FFImageLoading.Platform.dll
Exception thrown: 'System.NullReferenceException' in FFImageLoading.Platform.dll
Exception thrown: 'System.NullReferenceException' in FFImageLoading.Platform.dll
Exception thrown: 'System.NullReferenceException' in FFImageLoading.Platform.dll
Exception thrown: 'System.NullReferenceException' in System.Private.CoreLib.dll
Exception thrown: 'System.NullReferenceException' in System.Private.CoreLib.dll
Exception thrown: 'System.NullReferenceException' in System.Private.CoreLib.dll
Exception thrown: 'System.NullReferenceException' in System.Private.CoreLib.dll
Exception thrown: 'System.NullReferenceException' in System.Private.CoreLib.dll
Exception thrown: 'System.NullReferenceException' in System.Private.CoreLib.dll
Image loading failed: resource://SharedSvgSample.Resources.camera.svg?assembly=SharedSvgSample,%20Version=1.0.0.0,%20Culture=neutral,%20PublicKeyToken=null;(size=0x100,dip=True,type=SvgDataResolver)Image loading failed: resource://SharedSvgSample.Resources.fingerprint.svg?assembly=SharedSvgSample,%20Version=1.0.0.0,%20Culture=neutral,%20PublicKeyToken=null;(size=0x100,dip=True,type=SvgDataResolver)Image loading failed: resource://SharedSvgSample.Resources.bug.svg?assembly=SharedSvgSample,%20Version=1.0.0.0,%20Culture=neutral,%20PublicKeyToken=null;(size=0x100,dip=True,type=SvgDataResolver)   at FFImageLoading.Work.PlatformImageLoaderTask`1.<GenerateImageFromDecoderContainerAsync>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at FFImageLoading.Work.ImageLoaderTask`3.<GenerateImageAsync>d__105.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at FFImageLoading.Work.ImageLoaderTask`3.<RunAsync>d__109.MoveNext()   at FFImageLoading.Work.PlatformImageLoaderTask`1.<GenerateImageFromDecoderContainerAsync>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at FFImageLoading.Work.ImageLoaderTask`3.<GenerateImageAsync>d__105.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at FFImageLoading.Work.ImageLoaderTask`3.<RunAsync>d__109.MoveNext()   at FFImageLoading.Work.PlatformImageLoaderTask`1.<GenerateImageFromDecoderContainerAsync>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at FFImageLoading.Work.ImageLoaderTask`3.<GenerateImageAsync>d__105.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at FFImageLoading.Work.ImageLoaderTask`3.<RunAsync>d__109.MoveNext()[PERFORMANCE] RunAsync - NetManagedThreadId: 0, NativeThreadId: 0, Execution: 357 ms, Key: resource://SharedSvgSample.Resources.camera.svg?assembly=SharedSvgSample,%20Version=1.0.0.0,%20Culture=neutral,%20PublicKeyToken=null;(size=0x100,dip=True,type=SvgDataResolver)[PERFORMANCE] RunAsync - NetManagedThreadId: 0, NativeThreadId: 0, Execution: 354 ms, Key: resource://SharedSvgSample.Resources.fingerprint.svg?assembly=SharedSvgSample,%20Version=1.0.0.0,%20Culture=neutral,%20PublicKeyToken=null;(size=0x100,dip=True,type=SvgDataResolver)[PERFORMANCE] RunAsync - NetManagedThreadId: 0, NativeThreadId: 0, Execution: 594 ms, Key: resource://SharedSvgSample.Resources.bug.svg?assembly=SharedSvgSample,%20Version=1.0.0.0,%20Culture=neutral,%20PublicKeyToken=null;(size=0x100,dip=True,type=SvgDataResolver)The thread 0x5094 has exited with code 0 (0x0).
The thread 0x18e4 has exited with code 0 (0x0).
`

**Comment by FrancoisM** [comment]
I guess the variable `decoded ` is null in that [method](https://github.com/luberda-molinet/FFImageLoading/blob/16fbc09f9d5ae60f637c4cb5e662e5ebc1fe3b2a/source/FFImageLoading.Windows/Work/PlatformImageLoaderTask.cs#L100)

I'm loading svgs from resources.

**Comment by daniel-luberda** [comment]
The error is somewhere here: https://github.com/luberda-molinet/FFImageLoading/blob/master/source/FFImageLoading.Svg.Shared/SvgDataResolver.cs#L262-L297

I'll need some time to debug it though (I don't use Windows often)

**Comment by FrancoisM** [comment]
Just as a note, the reason I use UWP often is because it's so much faster to develop XF apps on UWP even though I only release to iOS and Android stores ;-)

Btw, I haven't spent any time on it as I downgraded back to 2.3.6 but I did push an iOS version of my app to beta testers with 2.4 in it and loading an uncached image was abnormally slow.

**Comment by FrancoisM** [comment]
Note that svg (as well as any cachedimage actually) do not systematically appear and can be missing on android as well with version 2.3.6. It wasn't the case before. So I suspect all this is related to Xamarin Forms which I updated to 3.0 at the same time.

**Comment by daniel-luberda** [comment]
Fixed. Stable nuget today.
