### ISSUE TITLE
Crash on UWP from OnShareTargetActivated

### ISSUE THREAD

**Issue by tamasszadvari** [luberda-molinet/FFImageLoading#1172]
### Description

If a UWP app is started by share activation, and any of the displayed views contains a CachedImage, the app crashes.

### Steps to Reproduce

1. Make a UWP project using Xamarin.Forms.
2. Override the OnShareTargetActivated method in the App.xaml.cs, to load the app as it was loaded from the OnLaunched method.
3. Add the Share Target declaration in the Package.appxmanifest file's Declarations section, with "Supports any file type" option.
4. Make the initial page to contain a CachedImage at least.
5. Select any file from the File Explorer, and Share with the app.

### Expected Behavior

The app starts, and displays the page.

### Actual Behavior

The app crashes.

### Basic Information

- Version with issue: 2.4.4.859
- Last known good version: -
- Platform: Xamarin.Forms, UWP

### StackTrace

System.NullReferenceException: Object reference not set to an instance of an object.
   at FFImageLoading.Helpers.MainThreadDispatcher.<Post>d__1.MoveNext()
   at Windows.ApplicationModel.Core.UnhandledError.Propagate()
   at Microsoft.AppCenter.Utils.ApplicationLifecycleHelper.<.ctor>b__17_1(Object sender, UnhandledErrorDetectedEventArgs eventArgs)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AppCenter.Utils.ApplicationLifecycleHelper.<.ctor>b__17_1(Object sender, UnhandledErrorDetectedEventArgs eventArgs)

**Comment by tamasszadvari** [comment]
It seems like that the error is originated from the "CoreApplication.MainView.CoreWindow.Dispatcher" call in the FFImageLoading.Windows project's MainThreadDispatcher class.

Getting the CoreApplication.MainView always throws a COMException for me, if I try to obtain it anywhere (either in a background thread, or on the UI thread, using the Device.BeginInvokeOnMainThread method).

But, the CoreApplication.GetCurrentView() method returns a not-null value, and by that I could get the Dispatcher.
Can you try it out, or send me a built package using that code?
