### ISSUE TITLE
ImageService.Instance.LoadEmbeddedResource - ArgumentNullException: Stream and Decoded

### ISSUE THREAD

**Issue by davidtabor90** [luberda-molinet/FFImageLoading#1347]
### Description
Hi,
I trying use FFImageLoading for caching image in Xamarin.Forms UWP application.
First what I try is "Preload" embedded resource but I received exception.

### Steps to Reproduce

App.xaml.cs
                ...
                // extra assemblies
                var assembliesToInclude = new List<Assembly>
                {
                    typeof(CachedImage).GetTypeInfo().Assembly,
                    typeof(CachedImageRenderer).GetTypeInfo().Assembly
                };

                Xamarin.Forms.Forms.Init(e, assembliesToInclude);

                CachedImageRenderer.Init();

                var config = new FFImageLoading.Config.Configuration()
                {
                    VerboseLogging = true,
                    VerbosePerformanceLogging = true,
                    VerboseMemoryCacheLogging = true,
                    VerboseLoadingCancelledLogging = true,
                    Logger = new CustomLogger(),
                };

                ImageService.Instance.Initialize(config);
                ...

### Actual Behavior

private async Task PreloadImages()
        {
            var resources = Assembly.GetExecutingAssembly().GetManifestResourceNames();

            foreach (var r in resources)
            {
                if (!r.EndsWith(".png")) continue;

                try
                {
                    await ImageService.Instance.LoadEmbeddedResource($"resource://{r}").PreloadAsync();
                }
                catch (Exception ex)
                {
                    _logger.Error($"LoaderPage.PreloadImages[{r}]", ex);
                }
            }
        }

Log:
FFImageLoading: Generating/retrieving image: resource://MyProject.info_ico.png
FFImageLoading: FFImageLoading: Image loading failed: resource://MyProject.info_ico.png
System.ArgumentNullException: Value cannot be null.
Parameter name: Stream and Decoded
   at FFImageLoading.DataResolvers.WrappedDataResolver.Resolve(String identifier, TaskParameter parameters, CancellationToken token)
   at FFImageLoading.Work.ImageLoaderTask`3.RunAsync()
Exception thrown: 'System.ArgumentNullException' in System.Private.CoreLib.dll

### Basic Information

- Version with issue: 2.4.11.982
- Platform: UWP

Thanks

**Comment by GreggAtCarfac** [comment]
I am having the same problem with loading SVG files this way. Does anybody know the solution?

**Comment by GreggAtCarfac** [comment]
I have found the solution. Uou have to give the Assembly with de recourcename.

await ImageService.Instance.LoadEmbeddedResource($"resource://{r}?assembly={Assembly.GetExecutingAssembly().GetName().Name}").PreloadAsync();
