### ISSUE TITLE
The CancellationTokenSource has been disposed.

### ISSUE THREAD

**Issue by martb1n** [luberda-molinet/FFImageLoading#186]
Hello. I have some problems with ListView with DataTemplate with CachedImage inside.
When I scroll ListView very fast and dynamically adding items, 
Can you anyone help me?
Xamarin.FFImageLoading version="2.0.7.1" 
Xamarin.FFImageLoading.Forms" version="2.0.7.1" 
Xamarin.Forms" version="2.1.0.6529"
I received this error

<pre>
Version Code: 100000
Version Name: 1.0.0
Android: 5.0
Android Build: 26.1.B.3.109
Manufacturer: Sony
Model: E2312
Thread: main-1
CrashReporter Key: 3D144E9D-A18B-19C6-FA88-6F695BAA2AB4D9C7BCFC
Start Date: Sat May 07 16:36:35 GMT+03:00 2016
Date: Sat May 07 16:38:29 GMT+03:00 2016

java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:811)
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1016)
	... 1 more
Caused by: md52ce486a14f4bcd95899665e9d932190b.JavaProxyThrowable: System.AggregateException: One or more errors occurred. ---> System.AggregateException: One or more errors occurred. ---> System.ObjectDisposedException: The CancellationTokenSource has been disposed.
  at System.Threading.CancellationTokenSource.Cancel (Boolean throwOnFirstException) [0x00000] in <filename unknown>:0 
  at System.Threading.CancellationTokenSource.Cancel () [0x00000] in <filename unknown>:0 
  at System.Threading.CancellationTokenSource.LinkedTokenCancelDelegate (System.Object source) [0x00007] in <filename unknown>:0 
  at System.Threading.CancellationCallbackInfo.ExecutionContextCallback (System.Object obj) [0x00007] in <filename unknown>:0 
  at System.Threading.CancellationCallbackInfo.ExecuteCallback () [0x0003c] in <filename unknown>:0 
  at System.Threading.CancellationTokenSource.CancellationCallbackCoreWork (CancellationCallbackCoreWorkArguments args) [0x0004a] in <filename unknown>:0 
  at System.Threading.CancellationTokenSource.ExecuteCallbackHandlers (Boolean throwOnFirstException) [0x000cb] in <filename unknown>:0 
  --- End of inner exception stack trace ---
  at System.Threading.CancellationTokenSource.ExecuteCallbackHandlers (Boolean throwOnFirstException) [0x0014f] in <filename unknown>:0 
  at System.Threading.CancellationTokenSource.NotifyCancellation (Boolean throwOnFirstException) [0x0005f] in <filename unknown>:0 
  at System.Threading.CancellationTokenSource.Cancel (Boolean throwOnFirstException) [0x00006] in <filename unknown>:0 
  at System.Threading.CancellationTokenSource.Cancel () [0x00000] in <filename unknown>:0 
  at System.Threading.CancellationTokenSource.LinkedTokenCancelDelegate (System.Object source) [0x00007] in <filename unknown>:0 
  at System.Threading.CancellationCallbackInfo.ExecutionContextCallback (System.Object obj) [0x00007] in <filename unknown>:0 
  at System.Threading.CancellationCallbackInfo.ExecuteCallback () [0x0003c] in <filename unknown>:0 
  at System.Threading.CancellationTokenSource.CancellationCallbackCoreWork (CancellationCallbackCoreWorkArguments args) [0x0004a] in <filename unknown>:0 
  at System.Threading.CancellationTokenSource.ExecuteCallbackHandlers (Boolean throwOnFirstException) [0x000cb] in <filename unknown>:0 
---> (Inner Exception #0) System.ObjectDisposedException: The CancellationTokenSource has been disposed.
  at System.Threading.CancellationTokenSource.Cancel (Boolean throwOnFirstException) [0x00000] in <filename unknown>:0 
  at System.Threading.CancellationTokenSource.Cancel () [0x00000] in <filename unknown>:0 
  at System.Threading.CancellationTokenSource.LinkedTokenCancelDelegate (System.Object source) [0x00007] in <filename unknown>:0 
  at System.Threading.CancellationCallbackInfo.ExecutionContextCallback (System.Object obj) [0x00007] in <filename unknown>:0 
  at System.Threading.CancellationCallbackInfo.ExecuteCallback () [0x0003c] in <filename unknown>:0 
  at System.Threading.CancellationTokenSource.CancellationCallbackCoreWork (CancellationCallbackCoreWorkArguments args) [0x0004a] in <filename unknown>:0 
  at System.Threading.CancellationTokenSource.ExecuteCallbackHandlers (Boolean throwOnFirstException) [0x000cb] in <filename unknown>:0 <---

  --- End of inner exception stack trace ---
  at System.Threading.CancellationTokenSource.ExecuteCallbackHandlers (Boolean throwOnFirstException) [0x0014f] in <filename unknown>:0 
  at System.Threading.CancellationTokenSource.NotifyCancellation (Boolean throwOnFirstException) [0x0005f] in <filename unknown>:0 
  at System.Threading.CancellationTokenSource.Cancel (Boolean throwOnFirstException) [0x00006] in <filename unknown>:0 
  at System.Threading.CancellationTokenSource.Cancel () [0x00000] in <filename unknown>:0 
  at FFImageLoading.Work.ImageLoaderTaskBase.Cancel () [0x00017] in <filename unknown>:0 
  at FFImageLoading.Forms.Droid.CachedImageRenderer.Cancel () [0x0001b] in <filename unknown>:0 
  at FFImageLoading.Forms.Droid.CachedImageRenderer.UpdateBitmap (FFImageLoading.Forms.CachedImage previous) [0x0007d] in <filename unknown>:0 
  at FFImageLoading.Forms.Droid.CachedImageRenderer.OnElementPropertyChanged (System.Object sender, System.ComponentModel.PropertyChangedEventArgs e) [0x0001a] in <filename unknown>:0 
  at (wrapper delegate-invoke) <Module>:invoke_void_object_PropertyChangedEventArgs (object,System.ComponentModel.PropertyChangedEventArgs)
  at Xamarin.Forms.BindableObject.OnPropertyChanged (System.String propertyName) [0x00012] in <filename unknown>:0 
  at Xamarin.Forms.Element.OnPropertyChanged (System.String propertyName) [0x00000] in <filename unknown>:0 
  at Xamarin.Forms.BindableObject.SetValueActual (Xamarin.Forms.BindableProperty property, Xamarin.Forms.BindablePropertyContext context, System.Object value, Boolean currentlyApplying, SetValueFlags attributes, Boolean silent) [0x000fb] in <filename unknown>:0 
  at Xamarin.Forms.BindableObject.SetValueCore (Xamarin.Forms.BindableProperty property, System.Object value, SetValueFlags attributes, SetValuePrivateFlags privateAttributes) [0x0014b] in <filename unknown>:0 
  at Xamarin.Forms.BindableObject.SetValue (Xamarin.Forms.BindableProperty property, System.Object value, Boolean fromStyle, Boolean checkAccess) [0x0005f] in <filename unknown>:0 
  at Xamarin.Forms.BindableObject.SetValue (Xamarin.Forms.BindableProperty property, System.Object value) [0x00000] in <filename unknown>:0 
  at FFImageLoading.Forms.CachedImage.set_Source (Xamarin.Forms.ImageSource value) [0x00000] in <filename unknown>:0 
  at Rent.App.Portable.Views.Cells.ApartmentCell.OnBindingContextChanged () [0x00021] in <filename unknown>:0 
  at Xamarin.Forms.BindableObject.BindingContextPropertyBindingPropertyChanged (Xamarin.Forms.BindableObject bindable, System.Object oldvalue, System.Object newvalue) [0x0001b] in <filename unknown>:0 
  at Xamarin.Forms.BindableObject.SetValueActual (Xamarin.Forms.BindableProperty property, Xamarin.Forms.BindablePropertyContext context, System.Object value, Boolean currentlyApplying, SetValueFlags attributes, Boolean silent) [0x0010e] in <filename unknown>:0 
  at Xamarin.Forms.BindableObject.SetValueCore (Xamarin.Forms.BindableProperty property, System.Object value, SetValueFlags attributes, SetValuePrivateFlags privateAttributes) [0x0014b] in <filename unknown>:0 
  at Xamarin.Forms.BindableObject.SetValue (Xamarin.Forms.BindableProperty property, System.Object value, Boolean fromStyle, Boolean checkAccess) [0x0005f] in <filename unknown>:0 
  at Xamarin.Forms.BindableObject.SetValue (Xamarin.Forms.BindableProperty property, System.Object value) [0x00000] in <filename unknown>:0 
  at Xamarin.Forms.BindableObject.set_BindingContext (System.Object value) [0x00000] in <filename unknown>:0 
  at Xamarin.Forms.TemplatedItemsList`2[TView,TItem].UpdateContent (Xamarin.Forms.TItem content, Int32 index, System.Object item) [0x00000] in <filename unknown>:0 
  at Xamarin.Forms.TemplatedItemsList`2[TView,TItem].UpdateContent (Xamarin.Forms.TItem content, Int32 index) [0x0000d] in <filename unknown>:0 
  at Xamarin.Forms.Platform.Android.ListViewAdapter.GetView (Int32 position, Android.Views.View convertView, Android.Views.ViewGroup parent) [0x00147] in <filename unknown>:0 
  at Android.Widget.BaseAdapter.n_GetView_ILandroid_view_View_Landroid_view_ViewGroup_ (IntPtr jnienv, IntPtr native__this, Int32 position, IntPtr native_convertView, IntPtr native_parent) [0x0001a] in <filename unknown>:0 
  at (wrapper dynamic-method) System.Object:a1e29333-caf9-4f07-a20d-ce7bbf6f4d97 (intptr,intptr,int,intptr,intptr)
---> (Inner Exception #0) System.AggregateException: One or more errors occurred. ---> System.ObjectDisposedException: The CancellationTokenSource has been disposed.
  at System.Threading.CancellationTokenSource.Cancel (Boolean throwOnFirstException) [0x00000] in <filename unknown>:0 
  at System.Threading.CancellationTokenSource.Cancel () [0x00000] in <filename unknown>:0 
  at System.Threading.CancellationTokenSource.LinkedTokenCancelDelegate (System.Object source) [0x00007] in <filename unknown>:0 
  at System.Threading.CancellationCallbackInfo.ExecutionContextCallback (System.Object obj) [0x00007] in <filename unknown>:0 
  at System.Threading.CancellationCallbackInfo.ExecuteCallback () [0x0003c] in <filename unknown>:0 
  at System.Threading.CancellationTokenSource.CancellationCallbackCoreWork (CancellationCallbackCoreWorkArguments args) [0x0004a] in <filename unknown>:0 
  at System.Threading.CancellationTokenSource.ExecuteCallbackHandlers (Boolean throwOnFirstException) [0x000cb] in <filename unknown>:0 
  --- End of inner exception stack trace ---
  at System.Threading.CancellationTokenSource.ExecuteCallbackHandlers (Boolean throwOnFirstException) [0x0014f] in <filename unknown>:0 
  at System.Threading.CancellationTokenSource.NotifyCancellation (Boolean throwOnFirstException) [0x0005f] in <filename unknown>:0 
  at System.Threading.CancellationTokenSource.Cancel (Boolean throwOnFirstException) [0x00006] in <filename unknown>:0 
  at System.Threading.CancellationTokenSource.Cancel () [0x00000] in <filename unknown>:0 
  at System.Threading.CancellationTokenSource.LinkedTokenCancelDelegate (System.Object source) [0x00007] in <filename unknown>:0 
  at System.Threading.CancellationCallbackInfo.ExecutionContextCallback (System.Object obj) [0x00007] in <filename unknown>:0 
  at System.Threading.CancellationCallbackInfo.ExecuteCallback () [0x0003c] in <filename unknown>:0 
  at System.Threading.CancellationTokenSource.CancellationCallbackCoreWork (CancellationCallbackCoreWorkArguments args) [0x0004a] in <filename unknown>:0 
  at System.Threading.CancellationTokenSource.ExecuteCallbackHandlers (Boolean throwOnFirstException) [0x000cb] in <filename unknown>:0 
---> (Inner Exception #0) System.ObjectDisposedException: The CancellationTokenSource has been disposed.
  at System.Threading.CancellationTokenSource.Cancel (Boolean throwOnFirstException) [0x00000] in <filename unknown>:0 
  at System.Threading.CancellationTokenSource.Cancel () [0x00000] in <filename unknown>:0 
  at System.Threading.CancellationTokenSource.LinkedTokenCancelDelegate (System.Object source) [0x00007] in <filename unknown>:0 
  at System.Threading.CancellationCallbackInfo.ExecutionContextCallback (System.Object obj) [0x00007] in <filename unknown>:0 
  at System.Threading.CancellationCallbackInfo.ExecuteCallback () [0x0003c] in <filename unknown>:0 
  at System.Threading.CancellationTokenSource.CancellationCallbackCoreWork (CancellationCallbackCoreWorkArguments args) [0x0004a] in <filename unknown>:0 
  at System.Threading.CancellationTokenSource.ExecuteCallbackHandlers (Boolean throwOnFirstException) [0x000cb] in <filename unknown>:0 <---
<---

	at md5b60ffeb829f638581ab2bb9b1a7f4f3f.ListViewAdapter.n_getView(Native Method)
	at md5b60ffeb829f638581ab2bb9b1a7f4f3f.ListViewAdapter.getView(ListViewAdapter.java:59)
	at android.widget.HeaderViewListAdapter.getView(HeaderViewListAdapter.java:220)
	at android.widget.AbsListView.obtainView(AbsListView.java:2344)
	at android.widget.ListView.makeAndAddView(ListView.java:1864)
	at android.widget.ListView.fillUp(ListView.java:732)
	at android.widget.ListView.fillGap(ListView.java:671)
	at android.widget.AbsListView.trackMotionScroll(AbsListView.java:4972)
	at android.widget.AbsListView$FlingRunnable.run(AbsListView.java:4516)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:767)
	at android.view.Choreographer.doCallbacks(Choreographer.java:580)
	at android.view.Choreographer.doFrame(Choreographer.java:549)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:753)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5319)
</pre>

And this
<pre> 
Version Code: 100000
Version Name: 1.0.0
Android: 5.0
Android Build: 26.1.B.3.109
Manufacturer: Sony
Model: E2312
Thread: main-1
CrashReporter Key: 3D144E9D-A18B-19C6-FA88-6F695BAA2AB4D9C7BCFC
Start Date: Sat May 07 16:34:12 GMT+03:00 2016
Date: Sat May 07 16:36:29 GMT+03:00 2016

java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:811)
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1016)
	... 1 more
Caused by: md52ce486a14f4bcd95899665e9d932190b.JavaProxyThrowable: System.AggregateException: One or more errors occurred. ---> System.ObjectDisposedException: The CancellationTokenSource has been disposed.
  at System.Threading.CancellationTokenSource.Cancel (Boolean throwOnFirstException) [0x00000] in <filename unknown>:0 
  at System.Threading.CancellationTokenSource.Cancel () [0x00000] in <filename unknown>:0 
  at System.Threading.CancellationTokenSource.LinkedTokenCancelDelegate (System.Object source) [0x00007] in <filename unknown>:0 
  at System.Threading.CancellationCallbackInfo.ExecutionContextCallback (System.Object obj) [0x00007] in <filename unknown>:0 
  at System.Threading.CancellationCallbackInfo.ExecuteCallback () [0x0003c] in <filename unknown>:0 
  at System.Threading.CancellationTokenSource.CancellationCallbackCoreWork (CancellationCallbackCoreWorkArguments args) [0x0004a] in <filename unknown>:0 
  at System.Threading.CancellationTokenSource.ExecuteCallbackHandlers (Boolean throwOnFirstException) [0x000cb] in <filename unknown>:0 
  --- End of inner exception stack trace ---
  at System.Threading.CancellationTokenSource.ExecuteCallbackHandlers (Boolean throwOnFirstException) [0x0014f] in <filename unknown>:0 
  at System.Threading.CancellationTokenSource.NotifyCancellation (Boolean throwOnFirstException) [0x0005f] in <filename unknown>:0 
  at System.Threading.CancellationTokenSource.Cancel (Boolean throwOnFirstException) [0x00006] in <filename unknown>:0 
  at System.Threading.CancellationTokenSource.Cancel () [0x00000] in <filename unknown>:0 
  at FFImageLoading.Work.ImageLoaderTaskBase.Cancel () [0x00017] in <filename unknown>:0 
  at FFImageLoading.Forms.Droid.CachedImageRenderer.Cancel () [0x0001b] in <filename unknown>:0 
  at FFImageLoading.Forms.Droid.CachedImageRenderer.UpdateBitmap (FFImageLoading.Forms.CachedImage previous) [0x0007d] in <filename unknown>:0 
  at FFImageLoading.Forms.Droid.CachedImageRenderer.OnElementPropertyChanged (System.Object sender, System.ComponentModel.PropertyChangedEventArgs e) [0x0001a] in <filename unknown>:0 
  at (wrapper delegate-invoke) <Module>:invoke_void_object_PropertyChangedEventArgs (object,System.ComponentModel.PropertyChangedEventArgs)
  at Xamarin.Forms.BindableObject.OnPropertyChanged (System.String propertyName) [0x00012] in <filename unknown>:0 
  at Xamarin.Forms.Element.OnPropertyChanged (System.String propertyName) [0x00000] in <filename unknown>:0 
  at Xamarin.Forms.BindableObject.SetValueActual (Xamarin.Forms.BindableProperty property, Xamarin.Forms.BindablePropertyContext context, System.Object value, Boolean currentlyApplying, SetValueFlags attributes, Boolean silent) [0x000fb] in <filename unknown>:0 
  at Xamarin.Forms.BindableObject.SetValueCore (Xamarin.Forms.BindableProperty property, System.Object value, SetValueFlags attributes, SetValuePrivateFlags privateAttributes) [0x0014b] in <filename unknown>:0 
  at Xamarin.Forms.BindableObject.SetValue (Xamarin.Forms.BindableProperty property, System.Object value, Boolean fromStyle, Boolean checkAccess) [0x0005f] in <filename unknown>:0 
  at Xamarin.Forms.BindableObject.SetValue (Xamarin.Forms.BindableProperty property, System.Object value) [0x00000] in <filename unknown>:0 
  at FFImageLoading.Forms.CachedImage.set_Source (Xamarin.Forms.ImageSource value) [0x00000] in <filename unknown>:0 
  at Rent.App.Portable.Views.Cells.ApartmentCell.OnBindingContextChanged () [0x00021] in <filename unknown>:0 
  at Xamarin.Forms.BindableObject.BindingContextPropertyBindingPropertyChanged (Xamarin.Forms.BindableObject bindable, System.Object oldvalue, System.Object newvalue) [0x0001b] in <filename unknown>:0 
  at Xamarin.Forms.BindableObject.SetValueActual (Xamarin.Forms.BindableProperty property, Xamarin.Forms.BindablePropertyContext context, System.Object value, Boolean currentlyApplying, SetValueFlags attributes, Boolean silent) [0x0010e] in <filename unknown>:0 
  at Xamarin.Forms.BindableObject.SetValueCore (Xamarin.Forms.BindableProperty property, System.Object value, SetValueFlags attributes, SetValuePrivateFlags privateAttributes) [0x0014b] in <filename unknown>:0 
  at Xamarin.Forms.BindableObject.SetValue (Xamarin.Forms.BindableProperty property, System.Object value, Boolean fromStyle, Boolean checkAccess) [0x0005f] in <filename unknown>:0 
  at Xamarin.Forms.BindableObject.SetValue (Xamarin.Forms.BindableProperty property, System.Object value) [0x00000] in <filename unknown>:0 
  at Xamarin.Forms.BindableObject.set_BindingContext (System.Object value) [0x00000] in <filename unknown>:0 
  at Xamarin.Forms.TemplatedItemsList`2[TView,TItem].UpdateContent (Xamarin.Forms.TItem content, Int32 index, System.Object item) [0x00000] in <filename unknown>:0 
  at Xamarin.Forms.TemplatedItemsList`2[TView,TItem].UpdateContent (Xamarin.Forms.TItem content, Int32 index) [0x0000d] in <filename unknown>:0 
  at Xamarin.Forms.Platform.Android.ListViewAdapter.GetView (Int32 position, Android.Views.View convertView, Android.Views.ViewGroup parent) [0x00147] in <filename unknown>:0 
  at Android.Widget.BaseAdapter.n_GetView_ILandroid_view_View_Landroid_view_ViewGroup_ (IntPtr jnienv, IntPtr native__this, Int32 position, IntPtr native_convertView, IntPtr native_parent) [0x0001a] in <filename unknown>:0 
  at (wrapper dynamic-method) System.Object:4a8aa677-3fab-4b43-a900-c874d2866923 (intptr,intptr,int,intptr,intptr)
---> (Inner Exception #0) System.ObjectDisposedException: The CancellationTokenSource has been disposed.
  at System.Threading.CancellationTokenSource.Cancel (Boolean throwOnFirstException) [0x00000] in <filename unknown>:0 
  at System.Threading.CancellationTokenSource.Cancel () [0x00000] in <filename unknown>:0 
  at System.Threading.CancellationTokenSource.LinkedTokenCancelDelegate (System.Object source) [0x00007] in <filename unknown>:0 
  at System.Threading.CancellationCallbackInfo.ExecutionContextCallback (System.Object obj) [0x00007] in <filename unknown>:0 
  at System.Threading.CancellationCallbackInfo.ExecuteCallback () [0x0003c] in <filename unknown>:0 
  at System.Threading.CancellationTokenSource.CancellationCallbackCoreWork (CancellationCallbackCoreWorkArguments args) [0x0004a] in <filename unknown>:0 
  at System.Threading.CancellationTokenSource.ExecuteCallbackHandlers (Boolean throwOnFirstException) [0x000cb] in <filename unknown>:0 <---

	at md5b60ffeb829f638581ab2bb9b1a7f4f3f.ListViewAdapter.n_getView(Native Method)
	at md5b60ffeb829f638581ab2bb9b1a7f4f3f.ListViewAdapter.getView(ListViewAdapter.java:59)
	at android.widget.HeaderViewListAdapter.getView(HeaderViewListAdapter.java:220)
	at android.widget.AbsListView.obtainView(AbsListView.java:2344)
	at android.widget.ListView.makeAndAddView(ListView.java:1864)
	at android.widget.ListView.fillDown(ListView.java:698)
	at android.widget.ListView.fillGap(ListView.java:662)
	at android.widget.AbsListView.trackMotionScroll(AbsListView.java:4972)
	at android.widget.AbsListView$FlingRunnable.run(AbsListView.java:4516)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:767)
	at android.view.Choreographer.doCallbacks(Choreographer.java:580)
	at android.view.Choreographer.doFrame(Choreographer.java:549)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:753)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5319)
</pre>

**Comment by molinch** [comment]
Could you try the 2.1 Alpha2 nuget packages that we uploaded?

**Comment by martb1n** [comment]
yes, I can. i'll try and tell you later.

**Comment by molinch** [comment]
Any news @martb1n ?

**Comment by martb1n** [comment]
Hi, sorry for delay. I have problems with dependencies in the app and I can't update them all now.

**Comment by daniel-luberda** [comment]
@martb1n I'll release two nuget version for Forms < 2.2 and Forms >= 2.2 soon.

**Comment by daniel-luberda** [comment]
@martb1n There's a new nuget which will work on any Xamarin.Forms version, so you can test it.

**Comment by molinch** [comment]
RC2 nuget just released, could you give it a try?

**Comment by molinch** [comment]
We have added fixes for it in recent release.
However there is a related Mono issue as I described in #205.

I will close this issue, we will continue investigations in #205

**Comment by martb1n** [comment]
Sorry, It's difficult to get steps to reproduced. I'll be watching in different issue(205) and will notify, if something change.
