### ISSUE TITLE
[UWP] NullReference Exception in a TabbedPage with 2 list of images

### ISSUE THREAD

**Issue by sbongiz** [luberda-molinet/FFImageLoading#291]
Exeption thrown: 
'System.NullReferenceException' in FFImageLoading.Forms.WinUWP.dll

StackTrace : 

```
Object reference not set to an instance of an object.  
  at FFImageLoading.Forms.WinUWP.CachedImageRenderer.ImageLoadingFinished(CachedImage element)
   at FFImageLoading.Forms.WinUWP.CachedImageRenderer.<>c__DisplayClass9_0.<UpdateSource>b__0(IScheduledWork work)
   at FFImageLoading.Work.ImageLoaderTaskBase.<>c__DisplayClass51_3.<ConfigureParameters>b__5()
   at FFImageLoading.Helpers.MainThreadDispatcher.<>c__DisplayClass3_0.<Post>b__0()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at FFImageLoading.Helpers.MainThreadDispatcher.<Post>d__3.MoveNext()
```

Our Code:

```
   <forms:CachedImage  Source="{Binding SelectedEventPrenotato.ImmagineLarga, StringFormat='http://www.my-website.com{0}'}" CacheDuration="1">
      </forms:CachedImage>
```

**Comment by daniel-luberda** [comment]
Could you try alpha nuget? Do you still experience it?

**Comment by angusbreno** [comment]
@daniel-luberda  Even with the latest package. 

If u run the sample app uwp (image chooser), u will see. https://github.com/NaylahProject/Naylah 

😢

**Comment by angusbreno** [comment]
The problem happens when the imagesource is changed and the page is navigated. The image loading not finished and if the page is back the imagecomponent reference goes to darkness, when the loading ends the reference don't exists anymore.

**Comment by daniel-luberda** [comment]
@angusbreno I'll try to push a fix for this soon (I don't use UWP often, sorry for a delay)

**Comment by daniel-luberda** [comment]
FFImageLoading 2.1.8-pre-146 nuget which contains discussed fixes released.

**Comment by daniel-luberda** [comment]
@sbongiz @angusbreno  Did it resolve you issues?

**Comment by angusbreno** [comment]
I will check and back here again. Thanks.

**Comment by daniel-luberda** [comment]
@angusbreno Is it working?

**Comment by angusbreno** [comment]
Sorry, i was busy these days... @erickriva Can u test this on NProject?

**Comment by daniel-luberda** [comment]
Please reopen if you still experience it.
