### ISSUE TITLE
App crashes with error: "Java.Lang.RuntimeException: Canvas: trying to use a recycled bitmap"

### ISSUE THREAD

**Issue by Emasoft** [luberda-molinet/FFImageLoading#297]
My app crashes with this error: "Java.Lang.RuntimeException: Canvas: trying to use a recycled bitmap"

I use FFImageLoading in a simple Listview with a custom Cell.

This is the crash log:

> Java.Lang.RuntimeException: Canvas: trying to use a recycled bitmap android.graphics.Bitmap@f41b99a
>   at --- End of managed Java.Lang.RuntimeException stack trace ---
>   at java.lang.RuntimeException: Canvas: trying to use a recycled bitmap android.graphics.Bitmap@f41b99a
>   at at android.graphics.Canvas.throwIfCannotDraw(Canvas.java:1270)
>   at at android.graphics.Canvas.drawBitmap(Canvas.java:1404)
>   at at android.graphics.drawable.BitmapDrawable.draw(BitmapDrawable.java:544)
>   at at android.widget.ImageView.onDraw(ImageView.java:1244)
>   at at android.view.View.draw(View.java:16178)
>   at at android.view.View.updateDisplayListIfDirty(View.java:15174)
>   at at android.view.View.draw(View.java:15948)
>   at at android.view.ViewGroup.drawChild(ViewGroup.java:3609)
>   at at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399)
>   at at android.view.View.updateDisplayListIfDirty(View.java:15169)
>   at at android.view.View.draw(View.java:15948)
>   at at android.view.ViewGroup.drawChild(ViewGroup.java:3609)
>   at at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399)
>   at at android.view.View.draw(View.java:16181)
>   at at android.view.View.updateDisplayListIfDirty(View.java:15174)
>   at at android.view.View.draw(View.java:15948)
>   at at android.view.ViewGroup.drawChild(ViewGroup.java:3609)
>   at at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399)
>   at at android.view.View.updateDisplayListIfDirty(View.java:15169)
>   at at android.view.View.draw(View.java:15948)
>   at at android.view.ViewGroup.drawChild(ViewGroup.java:3609)
>   at at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399)
>   at at android.view.View.updateDisplayListIfDirty(View.java:15169)
>   at at android.view.View.draw(View.java:15948)
>   at at android.view.ViewGroup.drawChild(ViewGroup.java:3609)
>   at at android.widget.ListView.drawChild(ListView.java:3416)
>   at at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399)
>   at at android.widget.AbsListView.dispatchDraw(AbsListView.java:2591)
>   at at android.widget.ListView.dispatchDraw(ListView.java:3411)
>   at at android.view.View.draw(View.java:16181)
>   at at android.widget.AbsListView.draw(AbsListView.java:4142)
>   at at android.view.View.updateDisplayListIfDirty(View.java:15174)
>   at at android.view.View.draw(View.java:15948)
>   at at android.view.ViewGroup.drawChild(ViewGroup.java:3609)
>   at at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399)
>   at at android.view.View.draw(View.java:16181)
>   at at android.view.View.updateDisplayListIfDirty(View.java:15174)
>   at at android.view.View.draw(View.java:15948)
>   at at android.view.ViewGroup.drawChild(ViewGroup.java:3609)
>   at at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399)
>   at at android.view.View.draw(View.java:16181)
>   at at android.view.View.updateDisplayListIfDirty(View.java:15174)
>   at at android.view.View.draw(View.java:15948)
>   at at android.view.ViewGroup.drawChild(ViewGroup.java:3609)
>   at at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399)
>   at at android.view.View.updateDisplayListIfDirty(View.java:15169)
>   at at android.view.View.draw(View.java:15948)
>   at at android.view.ViewGroup.drawChild(ViewGroup.java:3609)
>   at at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399)
>   at at android.view.View.updateDisplayListIfDirty(View.java:15169)
>   at at android.view.View.draw(View.java:15948)
>   at at android.view.ViewGroup.drawChild(ViewGroup.java:3609)
>   at at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399)
>   at at android.view.View.updateDisplayListIfDirty(View.java:15169)
>   at at android.view.View.draw(View.java:15948)
>   at at android.view.ViewGroup.drawChild(ViewGroup.java:3609)
>   at at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399)
>   at at android.view.View.updateDisplayListIfDirty(View.java:15169)
>   at at android.view.View.draw(View.java:15948)
>   at at android.view.ViewGroup.drawChild(ViewGroup.java:3609)
>   at at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399)
>   at at android.view.View.updateDisplayListIfDirty(View.java:15169)
>   at at android.view.View.draw(View.java:15948)
>   at at android.view.ViewGroup.drawChild(ViewGroup.java:3609)
>   at at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399)
>   at at android.view.View.updateDisplayListIfDirty(View.java:15169)
>   at at android.view.View.draw(View.java:15948)
>   at at android.view.ViewGroup.drawChild(ViewGroup.java:3609)
>   at at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399)
>   at at android.view.View.updateDisplayListIfDirty(View.java:15169)
>   at at android.view.View.draw(View.java:15948)
>   at at android.view.ViewGroup.drawChild(ViewGroup.java:3609)
>   at at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399)
>   at at android.view.View.draw(View.java:16181)
>   at at com.android.internal.policy.PhoneWindow$DecorView.draw(PhoneWindow.java:2690)
>   at at android.view.View.updateDisplayListIfDirty(View.java:15174)
>   at at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:281)
>   at at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:287)
>   at at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:322)
>   at at android.view.ViewRootImpl.draw(ViewRootImpl.java:2615)
>   at at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2434)
>   at at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2067)
>   at at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1107)
>   at at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6013)
>   at at android.view.Choreographer$CallbackRecord.run(Choreographer.java:858)
>   at at android.view.Choreographer.doCallbacks(Choreographer.java:670)
>   at at android.view.Choreographer.doFrame(Choreographer.java:606)
>   at at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
>   at at android.os.Handler.handleCallback(Handler.java:739)
>   at at android.os.Handler.dispatchMessage(Handler.java:95)
>   at at android.os.Looper.loop(Looper.java:148)
>   at at android.app.ActivityThread.main(ActivityThread.java:5417)
>   at at java.lang.reflect.Method.invoke(Native Method)
>   at at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
>   at at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
> 

My XAML main Page:

```xml
<ContentPage
	xmlns:cells="clr-namespace:MyApp;assembly=MyApp"
	xmlns="http://xamarin.com/schemas/2014/forms"
	xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
	x:Class="MyApp.SamplePage"
	Title="SamplePage">
	<ContentPage.Content>
		<ListView
			x:Name="MediaItemsListView"
			BackgroundColor="Transparent"
			SeparatorVisibility="None"
			HorizontalOptions="Center"
			VerticalOptions="Start"
			Margin="15,0,0,0"
			RowHeight="255">
			<ListView.ItemTemplate>
				<DataTemplate>
					<cells:CellEvento />
				</DataTemplate>
			</ListView.ItemTemplate>
		</ListView>
	</ContentPage.Content>
</ContentPage>

```

This is the main Page codebehind:

```c#
public partial class SamplePage : ContentPage
	{
		public SamplePage ()
		{
			InitializeComponent ();
			MediaItemsListView.ItemsSource = DataProvider.GetMediaItems ();
		}

		
	}

```

This is the custom Cell XAML:

```xml
<ViewCell x:Class="MyApp.CellEvento"
                   xmlns="http://xamarin.com/schemas/2014/forms"
                   xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
                   xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
                   xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
                   xmlns:pickee="clr-namespace:MyApp;assembly=MyApp">

   <AbsoluteLayout WidthRequest="344"
                    HeightRequest="244"
                    BackgroundColor="White"	>
        
<ffimageloading:CachedImage x:Name="ImageView"
                                    AbsoluteLayout.LayoutBounds="0,48,144,152"
                                    AbsoluteLayout.LayoutFlags="None"
                                    DownsampleToViewSize="true"
   				    LoadingPlaceholder="PlaceholderEventBadgePhotoGrayS.png" />

<ffimageloading:CachedImage x:Name="UserThumbnailView"
                                    WidthRequest="24"
                                    HeightRequest="24"
                                    AbsoluteLayout.LayoutBounds="298,211,24,24"
                                    AbsoluteLayout.LayoutFlags="None"
                                    DownsampleToViewSize="true"
                                    LoadingPlaceholder="PlaceholderEventBadgePhotoGrayS.png">
                      <ffimageloading:CachedImage.Transformations>
                                <fftransformations:CircleTransformation />
                     </ffimageloading:CachedImage.Transformations>
        </ffimageloading:CachedImage>
 
</AbsoluteLayout>
</ViewCell>
```

This is the custom cell codebehind:

```c#
	public partial class CellEvento : ViewCell
	{
		
			public CellEvento ()
			{
				InitializeComponent ();
			}

		protected override void OnBindingContextChanged ()
		{
                        base.OnBindingContextChanged ();
			var mediaItem = BindingContext as MediaItem;
			if (mediaItem != null)
				{
				    ImageView.Source = mediaItem.ImagePath ?? "";
				    UserThumbnailView.Source = mediaItem.AvatarPath ?? "";
			    }
		}
	}
```

This is the data provider class:

```c#
public static class DataProvider
{
  public static ObservableCollection<MediaItem> GetMediaItems ()
	 {
ObservableCollection<MediaItem> items = new ObservableCollection<MediaItem> ();
int counter = 0;
for (int index = 0; index < 20; index++)  {
  for (int i = 0; i < 20; i++) {
    var item = new MediaItem (
          "Image n." + counter,
          GetRandomImageUrlFlickr (288, 304),
          GetRandomAvatarPhotoUrlFlickr (120, 120),
          counter);
    items.Add (item);
    counter++;
				}
			}
	return items;
         }

		public static string GetRandomImageUrlFlickr (int width, int height)
		{
			return string.Format ("http://loremflickr.com/{1}/{2}/nature?filename={0}.jpg", Guid.NewGuid ().ToString ("N"), width, height);
		}
	
		public static string GetRandomAvatarPhotoUrlFlickr (int width, int height)
		{
			return string.Format ("http://loremflickr.com/{1}/{2}/girl,face/all?filename={0}.jpg", Guid.NewGuid ().ToString ("N"), width, height);
		}
}
```

And this is the mediaitem class:

```c#
public class MediaItem
	{
                public string Name { get; set; }
		public int Index { get; set; }
		public string ImagePath { get; set; }
		public string AvatarPath {get; set; }

		public MediaItem (string Name, string imagePath, string string avatarPath, int counter)
		{
			this.ImagePath = imagePath;
			this.AvatarPath = avatarPath;
			this.Name = counter.ToString ();
			this.Index = counter;
		}

		public override string ToString ()
		{
			return string.Format ("[MediaItem: Name={0}]", Name);
		}
		
		
	}

```
It is a pretty basic setup of a Xamarin.Forms app. Just ffImageLoader added to a Listview. The app works fine on iOS. But on Android it crashes.

This is the initialization code that I added to the MainActivity OnCreate method in the Droid project:

 ```c#
//FFImage initialization code ------
			FFImageLoading.Forms.Droid.CachedImageRenderer.Init ();
			var circlee = new FFImageLoading.Transformations.CircleTransformation ();
			var config = new FFImageLoading.Config.Configuration () {
				VerboseLogging = true,
				VerbosePerformanceLogging = true,
				VerboseMemoryCacheLogging = true,
				VerboseLoadingCancelledLogging = true,
				Logger = new CustomLogger (),
				MaxMemoryCacheSize = 10,
			};
			ImageService.Instance.Initialize (config);
			//-----------------------------------
 
```

And yes, I tried to remove the CircleTrasformation, but it makes no differences. After a few seconds of scroll, the app crashes.

The Android emulators I tried are many: official emulator of a Nexus 5 (standard setup, v19), Nexus 5 (with android v23), and Genymotion Nexus 5 (with android v19), and some more. All gives the same result: crash when scrolling after 2-5 seconds.

**Comment by Emasoft** [comment]
Notice that if I replace the image component "<ffimageloading:CachedImage>" with the standard one "<Image>", it works fine on all platforms. No crash at all on Android. So the problem lies in FFImageload. Please fix this bug.

**Comment by daniel-luberda** [comment]
Hi @Emasoft,

What is the reason of `MaxMemoryCacheSize = 10`? - this is **way too low** value to have caching working correctly.

**Comment by Emasoft** [comment]
@daniel-luberda Sorry, that was just a line of code I added to make a test reducing the cache to make the app to avoid going out of memory. I tried various sizes, but it didn't help. The bug was present before adding the line, and when the line is removed is still there.

**Comment by daniel-luberda** [comment]
Hi @Emasoft, 

Do you experience this issue with a newest stable? I cannot reproduce it currently. Is it possible to have a sample project with a reproduction?

**Comment by daniel-luberda** [comment]
@Emasoft  Do you experience it with newest stable?

**Comment by softsan** [comment]
It is reproducing on latest version (2.2.10):


`Java.Interop.JniEnvironmentCanvas: trying to use a recycled bitmap android.graphics.Bitmap@92557bd
Raw
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()<3fd174ff54b146228c505f23cf75ce71>:0
Java.Interop.JniEnvironment.InstanceMethods.CallNonvirtualVoidMethod(JniObjectReference instance, JniObjectReference type, JniMethodInfo method, JniArgumentValue* args)<bd30a18775d94dc8b6263aecd1ca9077>:0
Java.Interop.JniPeerMembers.JniInstanceMethods.InvokeVirtualVoidMethod(string encodedMember, IJavaPeerable self, JniArgumentValue* parameters)<bd30a18775d94dc8b6263aecd1ca9077>:0
Android.Views.View.Draw(Canvas canvas)<d855bac285f44dda8a0d8510b679b1e2>:0
Xamarin.Forms.Platform.Android.ScrollViewRenderer.Draw(Canvas canvas)<cc2cf9fed10c4c718bb9bb6c0f20842f>:0
Android.Views.View.n_Draw_Landroid_graphics_Canvas_(IntPtr jnienv, IntPtr native__this, IntPtr native_canvas)<d855bac285f44dda8a0d8510b679b1e2>:0
at (wrapper dynamic-method) System.Object:2e188e10-0305-4759-831c-36eb35b75d29 (intptr,intptr,intptr)
--- End of managed Java.Lang.RuntimeException stack trace ---
java.lang.RuntimeException: Canvas: trying to use a recycled bitmap android.graphics.Bitmap@92557bd
at android.graphics.Canvas.throwIfCannotDraw(Canvas.java:1270)
at android.graphics.Canvas.drawBitmap(Canvas.java:1404)
at android.graphics.drawable.BitmapDrawable.draw(BitmapDrawable.java:544)
at android.widget.ImageView.onDraw(ImageView.java:1259)
at android.view.View.draw(View.java:16199)
at android.view.View.updateDisplayListIfDirty(View.java:15196)
at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3596)
at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3576)
at android.view.View.updateDisplayListIfDirty(View.java:15156)
at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3596)
at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3576)
at android.view.View.updateDisplayListIfDirty(View.java:15156)
at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3596)
at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3576)
at android.view.View.updateDisplayListIfDirty(View.java:15156)
at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3596)
at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3576)
at android.view.View.updateDisplayListIfDirty(View.java:15156)
at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3596)
at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3576)
at android.view.View.updateDisplayListIfDirty(View.java:15156)
at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3596)
at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3576)
at android.view.View.updateDisplayListIfDirty(View.java:15156)
at android.view.View.draw(View.java:15969)
at android.view.ViewGroup.drawChild(ViewGroup.java:3612)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3402)
at android.view.View.draw(View.java:16202)
at android.view.View.updateDisplayListIfDirty(View.java:15196)
at android.view.View.draw(View.java:15969)
at android.view.ViewGroup.drawChild(ViewGroup.java:3612)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3402)
at android.view.View.updateDisplayListIfDirty(View.java:15191)
at android.view.View.draw(View.java:15969)
at android.view.ViewGroup.drawChild(ViewGroup.java:3612)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3402)
at android.view.View.draw(View.java:16202)
at android.widget.HorizontalScrollView.draw(HorizontalScrollView.java:1628)
at android.view.View.updateDisplayListIfDirty(View.java:15196)
at android.view.View.draw(View.java:15969)
at android.view.ViewGroup.drawChild(ViewGroup.java:3612)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3402)
at android.view.View.draw(View.java:16202)
at android.widget.ScrollView.draw(ScrollView.java:1715)
md5b60ffeb829f638581ab2bb9b1a7f4f3f.ScrollViewRenderer.n_draw(Native Method)
at md5b60ffeb829f638581ab2bb9b1a7f4f3f.ScrollViewRenderer.draw(ScrollViewRenderer.java:59)
at android.view.View.updateDisplayListIfDirty(View.java:15196)
at android.view.View.draw(View.java:15969)
at android.view.ViewGroup.drawChild(ViewGroup.java:3612)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3402)
at android.view.View.draw(View.java:16202)
at android.view.View.updateDisplayListIfDirty(View.java:15196)
at android.view.View.draw(View.java:15969)
at android.view.ViewGroup.drawChild(ViewGroup.java:3612)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3402)
at android.view.View.updateDisplayListIfDirty(View.java:15191)
at android.view.View.draw(View.java:15969)
at android.view.ViewGroup.drawChild(ViewGroup.java:3612)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3402)
at android.view.View.updateDisplayListIfDirty(View.java:15191)
at android.view.View.draw(View.java:15969)
at android.view.ViewGroup.drawChild(ViewGroup.java:3612)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3402)
at android.view.View.draw(View.java:16202)
at android.view.View.updateDisplayListIfDirty(View.java:15196)
at android.view.View.draw(View.java:15969)
at android.view.ViewGroup.drawChild(ViewGroup.java:3612)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3402)
at android.view.View.updateDisplayListIfDirty(View.java:15191)
at android.view.View.draw(View.java:15969)
at android.view.ViewGroup.drawChild(ViewGroup.java:3612)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3402)
at android.view.View.updateDisplayListIfDirty(View.java:15191)
at android.view.View.draw(View.java:15969)
at android.view.ViewGroup.drawChild(ViewGroup.java:3612)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3402)
at android.view.View.draw(View.java:16202)
at android.view.View.updateDisplayListIfDirty(View.java:15196)
at android.view.View.draw(View.java:15969)
at android.view.ViewGroup.drawChild(ViewGroup.java:3612)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3402)
at android.view.View.updateDisplayListIfDirty(View.java:15191)
at android.view.View.draw(View.java:15969)
at android.view.ViewGroup.drawChild(ViewGroup.java:3612)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3402)
at android.view.View.updateDisplayListIfDirty(View.java:15191)
at android.view.View.draw(View.java:15969)
at android.view.ViewGroup.drawChild(ViewGroup.java:3612)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3402)
at android.view.View.updateDisplayListIfDirty(View.java:15191)
at android.view.View.draw(View.java:15969)
at android.view.ViewGroup.drawChild(ViewGroup.java:3612)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3402)
at android.view.View.updateDisplayListIfDirty(View.java:15191)
at android.view.View.draw(View.java:15969)
at android.view.ViewGroup.drawChild(ViewGroup.java:3612)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3402)
at android.view.View.updateDisplayListIfDirty(View.java:15191)
at android.view.View.draw(View.java:15969)
at android.view.ViewGroup.drawChild(ViewGroup.java:3612)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3402)
at android.view.View.updateDisplayListIfDirty(View.java:15191)
at android.view.View.draw(View.java:15969)
at android.view.ViewGroup.drawChild(ViewGroup.java:3612)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3402)
at android.view.View.updateDisplayListIfDirty(View.java:15191)
at android.view.View.draw(View.java:15969)
at android.view.ViewGroup.drawChild(ViewGroup.java:3612)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3402)
at android.view.View.updateDisplayListIfDirty(View.java:15191)
at android.view.View.draw(View.java:15969)
at android.view.ViewGroup.drawChild(ViewGroup.java:3612)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3402)
at android.view.View.draw(View.java:16202)
at com.android.internal.policy.PhoneWindow$DecorView.draw(PhoneWindow.java:2690)
at android.view.View.updateDisplayListIfDirty(View.java:15196)
at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:281)
at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:287)
at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:322)
at android.view.ViewRootImpl.draw(ViewRootImpl.java:2627)
at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2446)
at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2079)
at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1119)
at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6060)
at android.view.Choreographer$CallbackRecord.run(Choreographer.java:858)
at android.view.Choreographer.doCallbacks(Choreographer.java:670)
at android.view.Choreographer.doFrame(Choreographer.java:606)
at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
at android.os.Handler.handleCallback(Handler.java:746)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:148)
at android.app.ActivityThread.main(ActivityThread.java:5443)
java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)`

**Comment by Contract16** [comment]
Hi, we're also getting this on latest (2.4.3.840), stack trace below:

```
java.lang.RuntimeException: Canvas: trying to use a recycled bitmap android.graphics.Bitmap@f01dac2 at android.graphics.BaseCanvas.throwIfCannotDraw(BaseCanvas.java:55
 at android.view.DisplayListCanvas.throwIfCannotDraw(DisplayListCanvas.java:226
 at android.view.RecordingCanvas.drawBitmap(RecordingCanvas.java:97
 at android.graphics.drawable.BitmapDrawable.draw(BitmapDrawable.java:529
 at android.widget.ImageView.onDraw(ImageView.java:1367
 at android.view.View.draw(View.java:19192
 at android.view.View.updateDisplayListIfDirty(View.java:18142
 at android.view.View.draw(View.java:18920
 at android.view.ViewGroup.drawChild(ViewGroup.java:4236
 at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4022
 at android.view.View.updateDisplayListIfDirty(View.java:18133
 at android.view.View.draw(View.java:18920
 at android.view.ViewGroup.drawChild(ViewGroup.java:4236
 at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4022
 at android.view.View.updateDisplayListIfDirty(View.java:18133
 at android.view.View.draw(View.java:18920
 at android.view.ViewGroup.drawChild(ViewGroup.java:4236
 at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4022
 at android.view.View.updateDisplayListIfDirty(View.java:18133
 at android.view.View.draw(View.java:18920
 at android.view.ViewGroup.drawChild(ViewGroup.java:4236
 at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4022
 at android.view.View.draw(View.java:19195
 at android.view.View.updateDisplayListIfDirty(View.java:18142
 at android.view.View.draw(View.java:18920
 at android.view.ViewGroup.drawChild(ViewGroup.java:4236
 at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4022
 at android.view.View.updateDisplayListIfDirty(View.java:18133
 at android.view.View.draw(View.java:18920
 at android.view.ViewGroup.drawChild(ViewGroup.java:4236
 at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4022
 at android.view.View.updateDisplayListIfDirty(View.java:18133
 at android.view.View.draw(View.java:18920
 at android.view.ViewGroup.drawChild(ViewGroup.java:4236
 at android.widget.ListView.drawChild(ListView.java:3590
 at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4022
 at android.widget.AbsListView.dispatchDraw(AbsListView.java:2638
 at android.widget.ListView.dispatchDraw(ListView.java:3585
 at android.view.View.draw(View.java:19195
 at android.widget.AbsListView.draw(AbsListView.java:4310
 at android.view.View.updateDisplayListIfDirty(View.java:18142
 at android.view.View.draw(View.java:18920
 at android.view.ViewGroup.drawChild(ViewGroup.java:4236
 at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4022
 at android.view.View.draw(View.java:19195
 at android.view.View.updateDisplayListIfDirty(View.java:18142
 at android.view.View.draw(View.java:18920
 at android.view.ViewGroup.drawChild(ViewGroup.java:4236
 at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4022
 at android.view.View.draw(View.java:19195
 at android.view.View.updateDisplayListIfDirty(View.java:18142
 at android.view.View.draw(View.java:18920
 at android.view.ViewGroup.drawChild(ViewGroup.java:4236
 at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4022
 at android.view.View.updateDisplayListIfDirty(View.java:18133
 at android.view.View.draw(View.java:18920
 at android.view.ViewGroup.drawChild(ViewGroup.java:4236
 at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4022
 at android.view.View.updateDisplayListIfDirty(View.java:18133
 at android.view.View.draw(View.java:18920
 at android.view.ViewGroup.drawChild(ViewGroup.java:4236
 at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4022
 at android.view.View.draw(View.java:19195
 at android.view.View.updateDisplayListIfDirty(View.java:18142
 at android.view.View.draw(View.java:18920
 at android.view.ViewGroup.drawChild(ViewGroup.java:4236
 at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4022
 at android.view.View.draw(View.java:19195)[0:] PageHarness are belong to GONE at android.view.View.updateDisplayListIfDirty(View.java:18142
 at android.view.View.draw(View.java:18920
 at android.view.ViewGroup.drawChild(ViewGroup.java:4236
 at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4022
 at android.view.View.updateDisplayListIfDirty(View.java:18133
 at android.view.View.draw(View.java:18920
 at android.view.ViewGroup.drawChild(ViewGroup.java:4236
 at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4022
 at android.view.View.updateDisplayListIfDirty(View.java:18133
 at android.view.View.draw(View.java:18920
 at android.view.ViewGroup.drawChild(ViewGroup.java:4236
 at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4022
 at android.view.View.updateDisplayListIfDirty(View.java:18133
 at android.view.View.draw(View.java:18920
 at android.view.ViewGroup.drawChild(ViewGroup.java:4236
 at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4022
 at android.view.View.updateDisplayListIfDirty(View.java:18133)[0:] PageHarness are belong to GONE at android.view.View.draw(View.java:18920
 at android.view.ViewGroup.drawChild(ViewGroup.java:4236
 at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4022
 at android.view.View.updateDisplayListIfDirty(View.java:18133
 at android.view.View.draw(View.java:18920
 at android.view.ViewGroup.drawChild(ViewGroup.java:4236
 at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4022
 at android.view.View.updateDisplayListIfDirty(View.java:18133
 at android.view.View.draw(View.java:18920
 at android.view.ViewGroup.drawChild(ViewGroup.java:4236
 at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4022
 at android.view.View.draw(View.java:19195
 at com.android.internal.policy.DecorView.draw(DecorView.java:788
 at android.view.View.updateDisplayListIfDirty(View.java:18142
 at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:669
 at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:675
 at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:783
 at android.view.ViewRootImpl.draw(ViewRootImpl.java:2992
 at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2806
 at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2359
 at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1392
 at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6752
 at android.view.Choreographer$CallbackRecord.run(Choreographer.java:911
 at android.view.Choreographer.doCallbacks(Choreographer.java:723
 at android.view.Choreographer.doFrame(Choreographer.java:658
 at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:897
 at android.os.Handler.handleCallback(Handler.java:790
 at android.os.Handler.dispatchMessage(Handler.java:99
 at android.os.Looper.loop(Looper.java:164
 at android.app.ActivityThread.main(ActivityThread.java:6494
 at java.lang.reflect.Method.invoke(Native Method
 at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
```
