### ISSUE TITLE
Xamarin.FFImageLoading.svg.Forms latest pre-release doesnt work!

### ISSUE THREAD

**Issue by EmilAlipiev** [luberda-molinet/FFImageLoading#388]
When i install and build 2.2.6 pre233 version, I get compile error in Droid project as below
```

Severity    Code    Description Project File    Line    Suppression State
Error       Exception while loading assemblies: System.IO.FileNotFoundException: Could not load assembly 'FFImageLoading.Svg.Platform, Version=1.0.0.0, Culture=neutral, PublicKeyToken='. Perhaps it doesn't exist in the Mono for Android profile?
File name: 'FFImageLoading.Svg.Platform.dll'
   at Java.Interop.Tools.Cecil.DirectoryAssemblyResolver.Resolve(AssemblyNameReference reference, ReaderParameters parameters)
   at Xamarin.Android.Tasks.ResolveAssemblies.AddAssemblyReferences(ICollection`1 assemblies, AssemblyDefinition assembly, Boolean topLevel)
   at Xamarin.Android.Tasks.ResolveAssemblies.Execute()         
```

**Comment by EmilAlipiev** [comment]
nobody cares about this?

**Comment by daniel-luberda** [comment]
It was an issue with nuspec file, I'll fix this soon. Meanwhile you can add dlls manually (from unpacked nuget file).

**Comment by daniel-luberda** [comment]
It should be fixed. Could you try the newest prerelease?

**Comment by Emasoft** [comment]
I can't find the Nuget. I searched for "Xamarin.FFImageLoading.Svg.Forms" and "FFImageLoading.Svg.Forms", but there is nothing. 
Just the standard FFImageLoading.Forms (that contains no Svg namespaces).

**Comment by Emasoft** [comment]
Doesn't work on iOS too.

This line of code in my main project:
```csharp
GradientRect.Source  = SvgImageSource.FromStream( () => MyProjectAssembly.GetManifestResourceStream(@"MyProject.SVGAssets.GradientRect.svg"));
```

Throw this error on the iOS project:

```
MyProject.iOS[21310:1620790] Image loading failed: Stream_1;(size=0x0,dip=True)
System.NullReferenceException: Object reference not set to an instance of an object
  at FFImageLoading.Svg.Platform.SvgDataResolver+<Resolve>d__15.MoveNext () [0x0033d] in <2304ef31b4434e449a1ef66637195ac0>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in /Users/builder/data/lanes/3969/44931ae8/source/xamarin-macios/_ios-build/Library/Frameworks/Xamarin.iOS.framework/Versions/git/src/mono/mcs/class/referencesource/mscorlib/system/runtime/exceptionservices/exceptionservicescommon.cs:143 
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x00047] in /Users/builder/data/lanes/3969/44931ae8/source/xamarin-macios/_ios-build/Library/Frameworks/Xamarin.iOS.framework/Versions/git/src/mono/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:187 
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x0002e] in /Users/builder/data/lanes/3969/44931ae8/source/xamarin-macios/_ios-build/Library/Frameworks/Xamarin.iOS.framework/Versions/git/src/mono/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:156 
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x0000b] in /Users/builder/data/lanes/3969/44931ae8/source/xamarin-macios/_ios-build/Library/Frameworks/Xamarin.iOS.framework/Versions/git/src/mono/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:128 
  at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in /Users/builder/data/lanes/3969/44931ae8/source/xamarin-macios/_ios-build/Library/Frameworks/Xamarin.iOS.framework/Versions/git/src/mono/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:535 
  at FFImageLoading.Work.ImageLoaderTask`2+<RunAsync>d__109[TImageContainer,TImageView].MoveNext () [0x00278] in <50976d5642674b2a84359992fee1c359>:0 
```

**Comment by Emasoft** [comment]
@daniel-luberda Any update on this?

**Comment by daniel-luberda** [comment]
Hi @Emasoft. Are you sure that returned stream is not null? You can also try new `SvgImageSource.FromResource` method. 

Hi @EmilAlipiev. Any news?

**Comment by Emasoft** [comment]
@daniel-luberda I already tried FromResource. I also tried FromUrl adding file: prefix to the path, and every other possible method combination. Nothing seems to work.

**Comment by daniel-luberda** [comment]
`SvgImageSource.FromResource` is not the same as `ImageSource.FromResource`. You must use SvgImageSource specific methods.

**Comment by Emasoft** [comment]
@daniel-luberda Yes, I know that. I used SvgImageSource too. It doesn't work.

**Comment by daniel-luberda** [comment]
@Emasoft Could you provide full StackTrace?

**Comment by Emasoft** [comment]
I removed the NuGet package now, but I will try it as soon as possible. Anyway it is not different from the one I reported you above.

**Comment by daniel-luberda** [comment]
`NullReferenceException` is probably thrown because your custom provided stream is null. Please reopen if you have any more info or still experience this. Thanks
