### ISSUE TITLE
Unhandled exception: Java.Util.ConcurrentModificationException: Exception of type 'Java.Util.ConcurrentModificationException' during InvalidateCacheAsync (v2.2.6 - pre241)

### ISSUE THREAD

**Issue by d-rakviashvili** [luberda-molinet/FFImageLoading#408]
When calling InvalidateCacheAsync method, following unhandled exception is thrown:

Checked with latest prerelease (v2.2.6 - pre241), NuGet package
Note: Strange behavior: After few failed attempts, fifth-s or sixths method call attempt may be successful :)

Unhandled exception: Java.Util.ConcurrentModificationException: Exception of type 'Java.Util.ConcurrentModificationException' was thrown.
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in /Users/builder/data/lanes/3511/77cb8568/source/mono/mcs/class/referencesource/mscorlib/system/runtime/exceptionservices/exceptionservicescommon.cs:143 
  at Java.Interop.JniEnvironment+InstanceMethods.CallObjectMethod (Java.Interop.JniObjectReference instance, Java.Interop.JniMethodInfo method) [0x00084] in /Users/builder/data/lanes/3511/ce955cc0/source/Java.Interop/src/Java.Interop/Java.Interop/JniEnvironment.g.cs:11262 
  at Android.Runtime.JNIEnv.CallObjectMethod (System.IntPtr jobject, System.IntPtr jmethod) [0x00000] in /Users/builder/data/lanes/3511/ce955cc0/source/monodroid/src/Mono.Android/JNIEnv.g.cs:96 
  at System.Linq.Extensions+<ToEnumerator_Dispose>c__Iterator1.MoveNext () [0x00043] in /Users/builder/data/lanes/3511/ce955cc0/source/xamarin-android/src/Mono.Android/System.Linq/Extensions.cs:37 
  at System.Linq.Enumerable+<CastIterator>c__Iterator19`1[TResult].MoveNext () [0x00059] in /Users/builder/data/lanes/3511/77cb8568/source/mono/mcs/class/referencesource/System.Core/System/Linq/Enumerable.cs:942 
  at System.Linq.Enumerable+WhereSelectEnumerableIterator`2[TSource,TResult].MoveNext () [0x00078] in /Users/builder/data/lanes/3511/77cb8568/source/mono/mcs/class/referencesource/System.Core/System/Linq/Enumerable.cs:282 
  at FFImageLoading.Cache.ReuseBitmapDrawableCache`1[TValue].Clear () [0x00037] in C:\projects\ffimageloading\source\FFImageLoading.Droid\Cache\ReuseBitmapDrawableCache.cs:425 
  at FFImageLoading.Cache.ImageCache`1[TValue].Clear () [0x00000] in C:\projects\ffimageloading\source\FFImageLoading.Droid\Cache\ImageCache.cs:67 
  at FFImageLoading.ImageService.InvalidateMemoryCache () [0x00007] in C:\projects\ffimageloading\source\FFImageLoading.Shared\ImageService.cs:314 
  at ....Mobile.Droid.MainActivity.OnTrimMemory (Android.Content.TrimMemory level) [0x00001] in ...MainActivity.cs:105 
  at Android.App.Activity.n_OnTrimMemory_I (System.IntPtr jnienv, System.IntPtr native__this, System.Int32 native_level) [0x0000b] in /Users/builder/data/lanes/3511/ce955cc0/source/monodroid/src/Mono.Android/platforms/android-24/src/generated/Android.App.Activity.cs:4555 
  at (wrapper dynamic-method) System.Object:792ae0ca-8292-4889-8651-6c7fd597f34d (intptr,intptr,int)
  --- End of managed Java.Util.ConcurrentModificationException stack trace ---
java.util.ConcurrentModificationException
	at java.util.Hashtable$HashIterator.nextEntry(Hashtable.java:727)
	at java.util.Hashtable$KeyIterator.next(Hashtable.java:768)
	at md5980ff21153c34ddb17bcbe53e025627f.MainActivity.n_onTrimMemory(Native Method)
	at md5980ff21153c34ddb17bcbe53e025627f.MainActivity.onTrimMemory(MainActivity.java:39)
	at android.app.ActivityThread.handleTrimMemory(ActivityThread.java:4619)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1560)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:155)
	at android.app.ActivityThread.main(ActivityThread.java:5696)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1028)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:823)

**Comment by daniel-luberda** [comment]
@d-rakviashvili Thanks! It's fixed now.
