### ISSUE TITLE
System.TypeLoadException: Xamarin Forms PCL project on Windows Phone 8.1

### ISSUE THREAD

**Issue by jderrough** [luberda-molinet/FFImageLoading#435]
Hi,

When running a Xamarin Forms PCL project on Windows Phone 8.1, the following exception is raised (sorry for the truncated output, hope it's enough to get a clear picture):

```
System.TypeLoadException: Could not load type 'FFImageLoading.DownloadProgress' from assembly 'FFImageLoading, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.
   at FFImageLoading.Forms.WinRT.CachedImageRenderer.<UpdateSource>d__9.MoveNext()
   at System.Runtime.CompilerServices.AsyncVoidMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)
   at FFImageLoading.Forms.WinRT.CachedImageRenderer.UpdateSource()
   at FFImageLoading.Forms.WinRT.CachedImageRenderer.OnElementChanged(ElementCh
```

The PCL project references assemblies:
- FFImageLoading
- FFImageLoading.Forms
- FFImageLoading.Platform

The WinRT project references assemblies:
- FFImageLoading
- FFImageLoading.Forms
- FFImageLoading.Forms.WinRT
- FFImageLoading.Platform

FFImageLoading is managed with NuGet, version is 2.2.6 with Xamarin Forms 2.3.3.175.
CachedImageRenderer.Init() is called in the App.xaml.cs file, right after Xamarin.Forms.Forms.Init() call.
Tried reinstalling all FFImageLoading packages with NuGet in the shared project and in the platform specific project, the exception is still raised.

Thanks in advance for your help.

**Comment by jderrough** [comment]
Hi @daniel-luberda ,

I ended up updated all the packages of all the platform specific projects in the solution, perform a NuGet clear, cleaning up everything (manually deleting the bin and obj folders). Seemed to do the trick. :)

Thanks for you help.
