### ISSUE TITLE
UWP TintTransformation - DivideByZeroException

### ISSUE THREAD

**Issue by galadril** [luberda-molinet/FFImageLoading#549]
The Xaml is working on Android and IOS, but it gives exceptions on UWP:

# Xaml
```
<ffimageloading:CachedImage
                                WidthRequest="25" HeightRequest="25" Source="{Binding statusIcon}">
                                    <ffimageloading:CachedImage.Transformations>
                                        <fftransformations:TintTransformation EnableSolidColor="True" HexColor="#8BC34A" />
                                    </ffimageloading:CachedImage.Transformations>
                                </ffimageloading:CachedImage>

```

# Exception

```
Image loading failed: ic_queue_black.pngTintTransformation,R=139,G=195,B=74,A=255,HexColor=#8BC34A,EnableSolidColor=True
System.DivideByZeroException: Attempted to divide by zero.
   at FFImageLoading.Transformations.TintTransformation.ToReplacedColor(BitmapHolder bmp, Int32 r, Int32 g, Int32 b, Int32 a)
   at FFImageLoading.Transformations.TintTransformation.Transform(BitmapHolder source)
   at FFImageLoading.Transformations.TransformationBase.Transform(IBitmap source)
   at FFImageLoading.Work.PlatformImageLoaderTask`1.<GenerateImageAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at FFImageLoading.Work.ImageLoaderTask`2.<RunAsync>d__109.MoveNext()
```

The image shows when I remove the TintTransformation, so it can find the image file resouce!

**Comment by galadril** [comment]
I now work around it by disabling the tint transformation on Windows:


```

                                <ffimageloading:CachedImage
                                WidthRequest="25" HeightRequest="25" Source="{Binding statusIcon}">
                                    <ffimageloading:CachedImage.Transformations>
                                        <fftransformations:TintTransformation HexColor="#8BC34A" >
                                            <fftransformations:TintTransformation.EnableSolidColor>
                                                <OnPlatform x:TypeArguments="x:Boolean">
                                                    <OnPlatform.iOS>True</OnPlatform.iOS>
                                                    <OnPlatform.Android>True</OnPlatform.Android>
                                                    <OnPlatform.WinPhone>False</OnPlatform.WinPhone>
                                                </OnPlatform>
                                            </fftransformations:TintTransformation.EnableSolidColor>
                                        </fftransformations:TintTransformation>
                                    </ffimageloading:CachedImage.Transformations>
                                </ffimageloading:CachedImage>

```

**Comment by MayeoinBread** [comment]
I've just started coming across this issue now. I've narrowed it down to using .png's with transparency, and having EnableSolidColor set to true in the transformation.

If I disable EnableSolidColor, there's no error, and the images then show although the transform just acts across the whole image (including the transparent parts, which is undesirable... see first image).

Purely a Windows problem, as the same setup works perfectly on Android with or without EnableSolidColor (see second picture)

![image](https://cloud.githubusercontent.com/assets/22642663/26659572/939e0f1c-4669-11e7-9d3b-11c8b97598c9.png)
![image](https://cloud.githubusercontent.com/assets/22642663/26659624/f8bd2cf2-4669-11e7-8dfa-c841e7089add.png)

**Comment by daniel-luberda** [comment]
It may be related to this: https://github.com/luberda-molinet/FFImageLoading/issues/384

Transformation source is here: https://github.com/luberda-molinet/FFImageLoading/blob/master/source/FFImageLoading.Transformations.Windows/TintTransformation.cs

Any clues?

**Comment by daniel-luberda** [comment]
Fixed :)
