### ISSUE TITLE
UWP Crash in 2.2.10-pre408

### ISSUE THREAD

**Issue by iWeaverMan** [luberda-molinet/FFImageLoading#638]
at FFImageLoading.Forms.WinUWP.CachedImageRenderer.<UpdateSource>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)
   at System.Threading.WinRTSynchronizationContext.Invoker.InvokeCore()

change source in reuse list cell: null, fileSource, null, fileSource

**Comment by iWeaverMan** [comment]
2.2.10-pre-438 without changes
Also occurs when resizing

**Comment by daniel-luberda** [comment]
I'll need full stack trace or reproduction to debug this. Please reopen if there are more details. Thanks.
