### ISSUE TITLE
Lot of "lamp target GC heap from" and Java.lang.outofmemory

### ISSUE THREAD

**Issue by lfongaroScp** [luberda-molinet/FFImageLoading#641]
Hi,

I use your library in my RecyclerView. Each of my custom RecyclerView.Adapter show an image. This image it is always on the disk as file .jpg or it must be downloaded. I use this code to retrieve the image
```
ImageService.Instance.LoadStream((t) => {
                    return db.GetImageStream(IdImg);
}).CacheKey(IdImg).LoadingPlaceholder(_pathPlaceHolder).Into(viewHolder.imageView);
```
I cannot use FFImageLoading to download the image, instead I download it, save on the disk and return a "Task.FromResult<Stream>(new FileStream(pathImage, FileMode.Open));".

It works, but If I scroll after 20-30 cell my app start to print 
`Clamp target GC heap from xxx MB to yyy MB `
And then print an 

> Java.Lang.OutOfMemoryError: Failed to allocate [...]
>
The app not crash, but the library no longer show new UIImageView.

Can you check? I use a MOTO g3 with Android 6.0 on.

**Comment by daniel-luberda** [comment]
Are you sure you release / dispose all resources properly in `GetImageStream` method? It looks like something in there doesn't do that properly.

**Comment by lfongaroScp** [comment]
Hi,
Thanks for the reply. If the image is on the device (and I test the library with this condition) that method create the stream as:
`return Task.FromResult<Stream>(new FileStream(pathImage, FileMode.Open));`

pathImage is created with this line of code:
`Path.Combine(_basePath, idImg + ".jpg")`

Regards,

**Comment by lfongaroScp** [comment]
I update my original post. Sorry, but english is not my native language.
After a couple of try I get a better log

```
Java.Lang.OutOfMemoryError: Failed to allocate a 777612 byte allocation with 59152 free bytes and 57KB until OOM
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <3fd174ff54b146228c505f23cf75ce71>:0 
  at Java.Interop.JniEnvironment+StaticMethods.CallStaticObjectMethod (Java.Interop.JniObjectReference type, Java.Interop.JniMethodInfo method, Java.Interop.JniArgumentValue* args) [0x00069] in <bd30a18775d94dc8b6263aecd1ca9077>:0 
  at Java.Interop.JniPeerMembers+JniStaticMethods.InvokeObjectMethod (System.String encodedMember, Java.Interop.JniArgumentValue* parameters) [0x00018] in <bd30a18775d94dc8b6263aecd1ca9077>:0 
  at Android.Graphics.BitmapFactory.DecodeStream (System.IO.Stream is, Android.Graphics.Rect outPadding, Android.Graphics.BitmapFactory+Options opts) [0x00070] in <d855bac285f44dda8a0d8510b679b1e2>:0 
  at Android.Graphics.BitmapFactory+<>c__DisplayClass33_0.<DecodeStreamAsync>b__0 () [0x00000] in <d855bac285f44dda8a0d8510b679b1e2>:0 
  at System.Threading.Tasks.Task`1[TResult].InnerInvoke () [0x0000f] in <3fd174ff54b146228c505f23cf75ce71>:0 
  at System.Threading.Tasks.Task.Execute () [0x00010] in <3fd174ff54b146228c505f23cf75ce71>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <3fd174ff54b146228c505f23cf75ce71>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <3fd174ff54b146228c505f23cf75ce71>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <3fd174ff54b146228c505f23cf75ce71>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <3fd174ff54b146228c505f23cf75ce71>:0 
  at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <3fd174ff54b146228c505f23cf75ce71>:0 
  at FFImageLoading.PlatformImageLoaderTask`1+<PlatformGenerateImageAsync>d__7[TImageView].MoveNext () [0x00496] in C:\projects\ffimageloading\source\FFImageLoading.Droid\Work\PlatformImageLoadingTask.cs:186 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <3fd174ff54b146228c505f23cf75ce71>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <3fd174ff54b146228c505f23cf75ce71>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <3fd174ff54b146228c505f23cf75ce71>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <3fd174ff54b146228c505f23cf75ce71>:0 
  at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <3fd174ff54b146228c505
f23cf75ce71>:0 
  at FFImageLoading.Work.ImageLoaderTask`2+<RunAsync>d__109[TImageContainer,TImageView].MoveNext () [0x0043f] in C:\projects\ffimageloading\source\FFImageLoading.Common\Work\ImageLoaderTask.cs:453 
  --- End of managed Java.Lang.OutOfMemoryError stack trace ---
java.lang.OutOfMemoryError: Failed to allocate a 777612 byte allocation with 59152 free bytes and 57KB until OOM
	at dalvik.system.VMRuntime.newNonMovableArray(Native Method)
	at android.graphics.BitmapFactory.nativeDecodeStream(Native Method)
	at android.graphics.BitmapFactory.decodeStreamInternal(BitmapFactory.java:635)
	at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:611)
```

I check also the library code. I am not so good in software develop and I have not years of experience, but maybe the problem is this:
```
if (_clearCacheOnOutOfMemory && ex is OutOfMemoryException)
                    {
                        MemoryCache.Clear();
                    }
```
maybe MemoryCache.Clear() isn't enough and the library must do an explicit call to Garbage Collector (GC.Collect()). In Xamarin.Android the GC see the bitmap only as a reference :-(

**Comment by lfongaroScp** [comment]
I can confirm that if you add GC.Collect() the problem is resolved.
I download the project, add the row and update the target Android SDK, I got the dll and add to my app.

I guess it's not a very good idea the explicit call to the GC, but I don't know a better solution. 

I hope it helps,
regards

**Comment by daniel-luberda** [comment]
if `GC.Collect()` resolves your issues its probably Xamarin issue, not FFImageLoading. I'll close this one then. Cheers.
