### ISSUE TITLE
Lot of errors while compiling release build

### ISSUE THREAD

**Issue by peppe130** [luberda-molinet/FFImageLoading#748]
Hi,

I'm using the latest version of this library. While compiling the release build of my App, I can see those errors in the output:

```c#
System.InvalidOperationException: Operation is not valid due to the current state of the object.
   at Mono.Cecil.ModuleDefinition.ReadSymbols(ISymbolReader reader)
   at Mono.Cecil.ModuleReader.ReadSymbols(ModuleDefinition module, ReaderParameters parameters)
   at Mono.Cecil.ModuleReader.CreateModule(Image image, ReaderParameters parameters)
   at Mono.Cecil.ModuleDefinition.ReadModule(String fileName, ReaderParameters parameters)
   at Java.Interop.Tools.Cecil.DirectoryAssemblyResolver.ReadAssembly(String file)
Failed to read 'C:\VisualStudioProjects\Projects\comune\Comune\Comune.Android\obj\Release\linksrc\FFImageLoading.Platform.dll' with debugging symbols. Retrying to load it without it. Error details are logged below.
System.InvalidOperationException: Operation is not valid due to the current state of the object.
   at Mono.Cecil.ModuleDefinition.ReadSymbols(ISymbolReader reader)
   at Mono.Cecil.ModuleReader.ReadSymbols(ModuleDefinition module, ReaderParameters parameters)
   at Mono.Cecil.ModuleReader.CreateModule(Image image, ReaderParameters parameters)
   at Mono.Cecil.ModuleDefinition.ReadModule(String fileName, ReaderParameters parameters)
   at Java.Interop.Tools.Cecil.DirectoryAssemblyResolver.ReadAssembly(String file)
Failed to read 'C:\VisualStudioProjects\Projects\comune\Comune\Comune.Android\obj\Release\linksrc\FFImageLoading.Transformations.dll' with debugging symbols. Retrying to load it without it. Error details are logged below.
System.InvalidOperationException: Operation is not valid due to the current state of the object.
   at Mono.Cecil.ModuleDefinition.ReadSymbols(ISymbolReader reader)
   at Mono.Cecil.ModuleReader.ReadSymbols(ModuleDefinition module, ReaderParameters parameters)
   at Mono.Cecil.ModuleReader.CreateModule(Image image, ReaderParameters parameters)
   at Mono.Cecil.ModuleDefinition.ReadModule(String fileName, ReaderParameters parameters)
   at Java.Interop.Tools.Cecil.DirectoryAssemblyResolver.ReadAssembly(String file)
Failed to read 'C:\VisualStudioProjects\Projects\comune\Comune\Comune.Android\obj\Release\android\assets\FFImageLoading.Forms.Droid.dll' with debugging symbols. Retrying to load it without it. Error details are logged below.
System.InvalidOperationException: Operation is not valid due to the current state of the object.
   at Mono.Cecil.ModuleDefinition.ReadSymbols(ISymbolReader reader)
   at Mono.Cecil.ModuleReader.ReadSymbols(ModuleDefinition module, ReaderParameters parameters)
   at Mono.Cecil.ModuleReader.CreateModule(Image image, ReaderParameters parameters)
   at Mono.Cecil.ModuleDefinition.ReadModule(String fileName, ReaderParameters parameters)
   at Java.Interop.Tools.Cecil.DirectoryAssemblyResolver.ReadAssembly(String file)
Failed to read 'C:\VisualStudioProjects\Projects\comune\Comune\Comune.Android\obj\Release\android\assets\FFImageLoading.Platform.dll' with debugging symbols. Retrying to load it without it. Error details are logged below.
System.InvalidOperationException: Operation is not valid due to the current state of the object.
   at Mono.Cecil.ModuleDefinition.ReadSymbols(ISymbolReader reader)
   at Mono.Cecil.ModuleReader.ReadSymbols(ModuleDefinition module, ReaderParameters parameters)
   at Mono.Cecil.ModuleReader.CreateModule(Image image, ReaderParameters parameters)
   at Mono.Cecil.ModuleDefinition.ReadModule(String fileName, ReaderParameters parameters)
   at Java.Interop.Tools.Cecil.DirectoryAssemblyResolver.ReadAssembly(String file)
Failed to read 'C:\VisualStudioProjects\Projects\comune\Comune\Comune.Android\obj\Release\android\assets\FFImageLoading.Transformations.dll' with debugging symbols. Retrying to load it without it. Error details are logged below.
System.InvalidOperationException: Operation is not valid due to the current state of the object.
   at Mono.Cecil.ModuleDefinition.ReadSymbols(ISymbolReader reader)
   at Mono.Cecil.ModuleReader.ReadSymbols(ModuleDefinition module, ReaderParameters parameters)
   at Mono.Cecil.ModuleReader.CreateModule(Image image, ReaderParameters parameters)
   at Mono.Cecil.ModuleDefinition.ReadModule(String fileName, ReaderParameters parameters)
   at Java.Interop.Tools.Cecil.DirectoryAssemblyResolver.ReadAssembly(String file)
```

Is it a problem with your library? Let me know, thanks.

**Comment by daniel-luberda** [comment]
Hi @peppe130,

What is your VS version? Is it Windows or Mac? It builds fine for me on both VS2017 / VS2017(Mac). Also every you can use nuget packages which are generated for every commit, here: https://ci.appveyor.com/project/daniel-luberda/ffimageloading/history

**Comment by peppe130** [comment]
I always keep my software up to date:
Visual Studio: 15.3.5
Xamarin: 4.7.9.45
Xamarin.Android.SDK: 7.4.5.1
Xamarin.iOS: 11.0.0.0

**Comment by daniel-luberda** [comment]
Is it a fresh clean & updated fork? I compiled it just fine on Windows. Which projects do you try to build?

**Comment by peppe130** [comment]
Yes, fresh, clean and updated. I'm trying to build Android solution.

**Comment by daniel-luberda** [comment]
Newest code compiles just fine on Windows and Mac, we use AppVeyor and all build are compiled on Windows. I don't think those errors are related to FFImageLoading at all (rather Visual studio issue)

**Comment by peppe130** [comment]
I switched to Mac. Thank you man for your work.
