### ISSUE TITLE
Binary XML file line #1: Error inflating class ffimageloading.views.ImageViewAsync

### ISSUE THREAD

**Issue by baberone** [luberda-molinet/FFImageLoading#879]
### Description

Hi

I'm using the ImageViewAsync in a List. Everything works fine in the emulator and on my test device (samsung j3 2017) but when submitting the app on Google Play, all tested devices fail with this error mesage:

android.view.InflateException: Binary XML file line #1: Binary XML file line #1: Error inflating class ffimageloading.views.ImageViewAsync
Caused by: android.view.InflateException: Binary XML file line #1: Error inflating class ffimageloading.views.ImageViewAsync
Caused by: java.lang.ClassNotFoundException: Didn't find class "ffimageloading.views.ImageViewAsync" on path: DexPathList[[zip file "/system/framework/android.test.runner.jar", zip file "/data/app/com.google.android.apps.mtaas.crawler-1/base.apk", zip file "/data/app/be.adiict.GiveMe5Droid-1/base.apk"],nativeLibraryDirectories=[/data/app/com.google.android.apps.mtaas.crawler-1/lib/arm64, /data/app/be.adiict.GiveMe5Droid-1/lib/arm, /system/fake-libs, /data/app/com.google.android.apps.mtaas.crawler-1/base.apk!/lib/armeabi-v7a, /data/app/be.adiict.GiveMe5Droid-1/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	at android.view.LayoutInflater.createView(LayoutInflater.java:609)

I was using version 2.3.1

Is this a normal behavior ?

**Comment by baberone** [comment]
Never mind. Updated to latest release (2.3.2), cleared obj and bin folder. 

All OK now !
