### ISSUE TITLE
RoundedCorners transformation results in an OutOfMemoryException

### ISSUE THREAD

**Issue by nielscup** [luberda-molinet/FFImageLoading#957]
### Description

RoundedCorners transformation results in an OutOfMemoryException

### Steps to Reproduce

Load about 100 images with rounded corners on a slow device (Samsung S4 in my test case)

### Expected Behavior

Display images with rounded corners

### Actual Behavior

Java.Lang.OutOfMemoryError

### Basic Information

**Possible solution:**
I think the following code ([line 75](https://github.com/luberda-molinet/FFImageLoading/blob/master/source/FFImageLoading.Transformations.Droid/RoundedTransformation.cs)) needs to be in a using statement:

`Bitmap bitmap = Bitmap.CreateBitmap((int)desiredWidth, (int)desiredHeight, Bitmap.Config.Argb8888);` 

**Full error message:** 

Transformation failed: RoundedTransformation,radius=12,cropWidthRatio=1,cropHeightRatio=1,borderSize=0,borderHexColor=
Java.Lang.OutOfMemoryError: Exception of type 'Java.Lang.OutOfMemoryError' was thrown.
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <657aa8fea4454dc898a9e5f379c58734>:0 
  at Java.Interop.JniEnvironment+StaticMethods.CallStaticObjectMethod (Java.Interop.JniObjectReference type, Java.Interop.JniMethodInfo method, Java.Interop.JniArgumentValue* args) [0x00069] in <e8c0e16a54534fa885244f0ad837c79e>:0 
  at Java.Interop.JniPeerMembers+JniStaticMethods.InvokeObjectMethod (System.String encodedMember, Java.Interop.JniArgumentValue* parameters) [0x00018] in <e8c0e16a54534fa885244f0ad837c79e>:0 
  at Android.Graphics.Bitmap.CreateBitmap (System.Int32 width, System.Int32 height, Android.Graphics.Bitmap+Config config) [0x00050] in /Users/builder/data/lanes/5749/75f8c683/source/xamarin-android/src/Mono.Android/obj/Release/android-26/mcw/Android.Graphics.Bitmap.cs:744 
  at FFImageLoading.Transformations.RoundedTransformation.ToRounded (Android.Graphics.Bitmap source, System.Single rad, System.Double cropWidthRatio, System.Double cropHeightRatio, System.Double borderSize, System.String borderHexColor) [0x00093] in C:\projects\ffimageloading\source\FFImageLoading.Transformations.Droid\RoundedTransformation.cs:75 
  at FFImageLoading.Transformations.RoundedTransformation.Transform (Android.Graphics.Bitmap sourceBitmap, System.String path, FFImageLoading.Work.ImageSource source, System.Boolean isPlaceholder, System.String key) [0x00000] in C:\projects\ffimageloading\source\FFImageLoading.Transformations.Droid\RoundedTransformation.cs:48 
  at FFImageLoading.Transformations.TransformationBase.Transform (FFImageLoading.Work.IBitmap bitmapHolder, System.String path, FFImageLoading.Work.ImageSource source, System.Boolean isPlaceholder, System.String key) [0x00007] in C:\projects\ffimageloading\source\FFImageLoading.Droid\Transformations\TransformationBase.cs:14 
  at FFImageLoading.PlatformImageLoaderTask`1+<TransformAsync>d__10[TImageView].MoveNext () [0x000b4] in C:\projects\ffimageloading\source\FFImageLoading.Droid\Work\PlatformImageLoadingTask.cs:138 
  --- End of managed Java.Lang.OutOfMemoryError stack trace ---
java.lang.OutOfMemoryError
	at android.graphics.Bitmap.nativeCreate(Native Method)
	at android.graphics.Bitmap.createBitmap(Bitmap.java:928)
	at android.graphics.Bitmap.createBitmap(Bitmap.java:901)
	at android.graphics.Bitmap.createBitmap(Bitmap.java:868)
	at dalvik.system.NativeStart.run(Native Method)

### Screenshots

na

### Reproduction Link / Code

na

**Comment by daniel-luberda** [comment]
Should be fixed now. Duplicate of #936
