### ISSUE TITLE
Java.Lang.ClassNotFoundException: android.support.media.ExifInterface

### ISSUE THREAD

**Issue by nielscup** [luberda-molinet/FFImageLoading#961]
### Description

When running my application I see a lot of these errors in the Application Output:

```
Java.Lang.ClassNotFoundException: android.support.media.ExifInterface ---> Java.Lang.ClassNotFoundException: Didn't find class "android.support.media.ExifInterface" on path: DexPathList[[zip file "/data/app/net.test.app/base.apk"],nativeLibraryDirectories=[/data/app/net.test.app/lib/arm, /system/fake-libs, /data/app/net.test.app/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]
   --- End of inner exception stack trace ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <657aa8fea4454dc898a9e5f379c58734>:0 
  at Java.Interop.JniEnvironment+StaticMethods.CallStaticObjectMethod (Java.Interop.JniObjectReference type, Java.Interop.JniMethodInfo method, Java.Interop.JniArgumentValue* args) [0x00069] in <e8c0e16a54534fa885244f0ad837c79e>:0 
  at Android.Runtime.JNIEnv.CallStaticObjectMethod (System.IntPtr jclass, System.IntPtr jmethod, Android.Runtime.JValue* parms) [0x00000] in /Users/builder/data/lanes/5749/75f8c683/source/xamarin-android/src/Mono.Android/Android.Runtime/JNIEnv.g.cs:562 
  at Android.Runtime.JNIEnv.CallStaticObjectMethod (System.IntPtr jclass, System.IntPtr jmethod, Android.Runtime.JValue[] parms) [0x00017] in /Users/builder/data/lanes/5749/75f8c683/source/xamarin-android/src/Mono.Android/Android.Runtime/JNIEnv.g.cs:568 
  at Android.Runtime.JNIEnv.FindClass (System.String classname) [0x00007] in /Users/builder/data/lanes/5749/75f8c683/source/xamarin-android/src/Mono.Android/Android.Runtime/JNIEnv.cs:606 
  at Android.Runtime.JNIEnv.FindClass (System.String className, System.IntPtr& cachedJniClassHandle) [0x00011] in /Users/builder/data/lanes/5749/75f8c683/source/xamarin-android/src/Mono.Android/Android.Runtime/JNIEnv.cs:620 
  at Android.Support.Media.ExifInterface.get_class_ref () [0x00000] in <b5e0204c53144360b3127b496915d1ca>:0 
  at Android.Support.Media.ExifInterface..ctor (System.IO.Stream inputStream) [0x0009c] in <b5e0204c53144360b3127b496915d1ca>:0 
  at FFImageLoading.Extensions.ExifExtensions.GetExifRotationDegrees (System.IO.Stream stream) [0x00002] in C:\projects\ffimageloading\source\FFImageLoading.Droid\Extensions\ExifExtensions.cs:13 
  at FFImageLoading.Decoders.BaseDecoder+<DecodeAsync>d__0.MoveNext () [0x001e1] in C:\projects\ffimageloading\source\FFImageLoading.Droid\Decoders\BaseDecoder.cs:60 
  --- End of managed Java.Lang.ClassNotFoundException stack trace ---
java.lang.ClassNotFoundException: android.support.media.ExifInterface
	at java.lang.Class.classForName(Native Method)
	at java.lang.Class.forName(Class.java:400)
Caused by: java.lang.ClassNotFoundException: Didn't find class "android.support.media.ExifInterface" on path: DexPathList[[zip file "/data/app/net.test.app/base.apk"],nativeLibraryDirectories=[/data/app/net.test.app/lib/arm, /system/fake-libs, /data/app/net.test.app/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	... 2 more
```

### Steps to Reproduce

Run application that includes CachedImages

### Expected Behavior

no error messages

### Actual Behavior

ref description

### Basic Information

- Version with issue: 2.3.4
- Platform: Xamarin.Forms Android

### Screenshots

none

### Reproduction Link / Code

none

**Comment by daniel-luberda** [comment]
You're  missing support library ExifInterface nuget package. Closing it, as it was removed from dependencies anyway in upcoming release (as it was buggy, so we replaced it with new exif parsing implementation).

**Comment by nielscup** [comment]
Any idea when the new version is available?

**Comment by daniel-luberda** [comment]
It's already available as a prerelease
